sudo: false
language: python
python:
  - "3.6"
  - "3.5-dev"
  - "pypy" #

before_install:
  - echo `ruby -v` is the ruby version
install:  
  - pip install argparse  
  - python setup.py sdist build
  - pip install nose-cov
script:
  - cd ./C-tamil && make all && make test && cd ..
  - ./unittest3 #naked tests
after_success:
  - pip install coveralls
  - coveralls
